### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by maxgerhardt**
## Check-list

- [X] Use a meaningful title for the Pull Request. Include the name of the package modified.
- [X] Test the change in your own code.

## Type of change

- [ ] Bug fix
- [X] Enhancement
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

Adds PlatformIO to build all examples with a representative of each declared compatible platform.

Compilation fails for the Pico because the main class is not available. Example code or libaries need to be patched for that.

In any case, the CI is unaffected by it.

**Note: Squash commits upon merging so that only one nice commit appears with a good name**

### CODE REVIEW

**Comment by GogoVega** [comment]
I wanted to add a CI but I had no idea how it worked.
Thank you again @maxgerhardt 🙂

**Comment by maxgerhardt** [comment]
Pico can also be removed from board list if that part is still under development.

**Comment by maxgerhardt** [comment]
PS: Took everything pretty much straight from examples: https://docs.platformio.org/en/latest/integration/ci/github-actions.html

**Comment by maxgerhardt** [comment]
Pico was removed from CI with comment for re-enabling it. CI should go through momentarily.

**Comment by maxgerhardt** [comment]
CI has completed with no problems: https://github.com/maxgerhardt/RFIDtoEEPROM/actions/runs/2424289877

**Comment by GogoVega** [comment]
Thanks again @maxgerhardt, can I merge it?

**Comment by maxgerhardt** [comment]
Sure, just remember to squash the commits when merging.

**Pull request merged**
